### ISSUE TITLE
Page Layout change width will not be changed via collab server

### ISSUE THREAD

**Issue by tedchou12** [MO-Movia/licit#8]
It seems like the collab server cannot correctly interpret the `SetDocAttr`, so the opposite side won't change.

```
Applications/MAMP/htdocs/prosemirror_server/server_9/node_modules/prosemirror-transform/dist/index.js:397
  if (!type) { throw new RangeError(("No step type " + (json.stepType) + " defined")) }
               ^

RangeError: No step type SetDocAttr defined
```

**Comment by tedchou12** [comment]
I think we need to add it to transform

**Comment by tedchou12** [comment]
sorry, seems like is okay for the collab server.
BUT, the Transform function will not work with: SetDocAttr.

**Comment by firmusoft** [comment]
This was a known issue, pended & now fixed and available in [fix_pagelayout_notworking](https://github.com/MO-Movia/licit/tree/fix_pagelayout_notworking).

**Comment by tedchou12** [comment]
@firmusoft 
Thank you!
Seems like the error still pops-up:
```
ted.chou@IITPC20-0109 prosemirror_parser % node main.js 
/Applications/MAMP/htdocs/prosemirror_server/server_12/prosemirror_parser/node_modules/prosemirror-transform/dist/index.js:396
  if (!type) { throw new RangeError(("No step type " + (json.stepType) + " defined")) }
               ^

RangeError: No step type SetDocAttr defined
    at Function.fromJSON (/Applications/MAMP/htdocs/prosemirror_server/server_12/prosemirror_parser/node_modules/prosemirror-transform/dist/index.js:396:22)
    at Object.<anonymous> (/Applications/MAMP/htdocs/prosemirror_server/server_12/prosemirror_parser/main.js:53:45)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
This is the package I am using:
https://github.com/tedchou12/prosemirror-server/tree/master/prosemirror_parser
`npm build`

I solved it by special handling, but if it could be native, it would be great:
```
for (var step_json of step_jsons) {
  step_json = JSON.parse(step_json)
  for (var step of step_json['steps']) {
    // change the page width with SetDocAttr
    if (step['stepType'] == 'SetDocAttr') {
      attrs[step['key']] = step['value']
    } else {
      var step = _prosemirrorTransform.Step.fromJSON(custom_schema, step)
      var result = step.apply(doc_node)
      if (result.failed) {

      } else {
        doc_node = result.doc
      }
    }
  }
}
```
